# Generated by Django 4.0.5 on 2022-07-12 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.BooleanField(choices=[(True, 'Compartir tu hogar'), (False, 'Buscar un lugar')])),
                ('nombre_pub', models.CharField(max_length=50)),
                ('direccion_pub', models.CharField(max_length=30)),
                ('fecha_pub', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.IntegerField()),
                ('info_general', models.TextField(max_length=500)),
                ('img', models.ImageField(default='template.jpg', upload_to='imagenes_publicaciones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
