# Generated by Django 4.0.5 on 2022-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.BooleanField()),
                ('nombre_pub', models.CharField(max_length=50)),
                ('direccion_pub', models.CharField(max_length=30)),
                ('fecha_pub', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.IntegerField()),
                ('info_general', models.TextField(max_length=500)),
                ('img', models.ImageField(default='N/A', upload_to='imagenes_publicaciones')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroUsuario',
        ),
    ]
